general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = wlopm --on
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = cw
}

listener {
    timeout = 330
    on-timeout = wlopm --off
    on-resume = wlopm --on && brightnessctl -r
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
