#!/usr/bin/env bash

# Strap 'dem boots

set -e

echo "Checking for Nix..."

if test ! "$(which nix)"; then
  echo ""
  echo "Attempting to install Nix..."

  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
fi

echo ""
echo "Good to go!"
