#!/usr/bin/env bash

# Link all the things!

set -e

cd "$(dirname "$0")/.."

DOTFILES=$HOME/.dotfiles

echo "Creating symlink for dotfiles"
if [[ ! -L "$DOTFILES" && ! -d "$DOTFILES" ]]
then
  ln -s "$(pwd)" $DOTFILES
fi

# Source: https://github.com/nicknisi/dotfiles/blob/master/install/link.sh
for file in $( find -H "$DOTFILES" -maxdepth 3 -name '*.symlink' ) ; do
  target="$HOME/.$( basename $file '.symlink' )"
  echo "Creating symlink for $file"
  ln -sf $file $target
done

# find the linkers and run them iteratively
find . -name link.sh | while read linker ; do sh -c "${linker}" ; done
