#!/usr/bin/env bash

CURR_HOST=$(cat /etc/hostname)
DOTFILES_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/.. &> /dev/null && pwd)
HOME_DIR="$DOTFILES_DIR/home"
HOSTS_DIR="$DOTFILES_DIR/hosts"
SCRIPT_DIR="$DOTFILES_DIR/script"

source "$SCRIPT_DIR/common.bash"

cmd=""
dry="0"

function help {
	echo "script/run [flags]"
	echo ""
	echo "Flags:"
	echo "  -h|--help   Show this help screen"
}

while [[ $# -gt 0 ]]; do
	case $1 in
		--dry|-n)
			cmd="log"
			dry="1"
			;;
		--help|-h)
			help
			exit 0
			;;
	esac

	shift
done

. "$HOSTS_DIR/$CURR_HOST.bash"

for h in "${PACKAGES[@]}"; do
	. "$HOME_DIR/$h/install.bash"
	. "$HOME_DIR/$h/link.bash"
done
