#!/usr/bin/env bash

CURR_HOST=$(cat /etc/hostname)
DOTFILES_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/.. &> /dev/null && pwd)
HELPERS_DIR="$DOTFILES_DIR/helpers"
HOME_DIR="$DOTFILES_DIR/home"
HOSTS_DIR="$DOTFILES_DIR/hosts"
SOURCE_DIR="$DOTFILES_DIR/.source"
SCRIPT_DIR="$DOTFILES_DIR/script"

source "$SCRIPT_DIR/common.bash"

function help {
  echo "script/run [flags]"
  echo ""
  echo "Flags:"
  echo "  -h|--help   Show this help screen"
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry|-n)
      cmd="log"
      dry="1"
      ;;
    --help|-h)
      help
      exit 0
      ;;
  esac

  shift
done

# shellcheck source=/dev/null
. "$HOSTS_DIR/$CURR_HOST.bash"

for h in "${PACKAGES[@]}"; do
  install_script="$HOME_DIR/$h/install.bash"
  link_script="$HOME_DIR/$h/link.bash"

  if [[ -f "$install_script" ]]; then
    # shellcheck source=/dev/null
    . "$install_script"
  fi

  if [[ -f "$link_script" ]]; then
    # shellcheck source=/dev/null
    . "$link_script"
  fi
done

link "$DOTFILES_DIR" "$HOME/.dotfiles"
