#!/usr/bin/env bash

# Install all the things! Set all the settings! Config all the configs!

set -e

if test "$(which nixos-rebuild)"; then
  echo "On NixOS, rebuilding system..."

  sudo nixos-rebuild switch --flake flake.nix
else
  echo "Not NixOS, using Home Manager..."

  nix run home-manager -- switch --impure --flake .
fi
